version: '3'
services:
  api:
    container_name: whatsapp-gateway
    build: .
    restart: on-failure
    ports:
      - "5001:5001"
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - "./wa_credentials:/app/wa_credentials"  
